name: Publish Docker Image to DockerHub
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI for Vue Application"]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
        (github.event.workflow_run.event == 'push' ||
        (github.event.workflow_run.event == 'pull_request' &&
         github.event.workflow_run.pull_request.merged == true)))
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: sjitzooi/template_library_frontend

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
